const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
function bindFastTap(el,handler){if(!el)return;el.onpointerup=e=>{e.preventDefault();e.stopPropagation();handler(e)};el.onclick=e=>{e.preventDefault();e.stopPropagation();if(e.detail===0)handler(e)}}
const store={
 get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},
 set(k,v){localStorage.setItem(k,JSON.stringify(v))}
};
let tasks=store.get('tide_tasks',[
 {time:'10:30 AM',title:'Call Rohan about campaign proposal',sub:'Follow-up · Buzz Media Fame',type:'Work',done:false},
 {time:'12:30 PM',title:'Content strategy review',day:'Today',sub:'Meeting · Cafe Monsoon team',type:'Work',done:false},
 {time:'2:15 PM',title:'Visit BMC — Ward office',sub:'Carry file #PL-284 and ID copy',type:'BMC',done:false},
 {time:'4:30 PM',title:'Review reels submitted by Aman',sub:'Team · 5 videos waiting',type:'Team',done:false},
 {time:'6:30 PM',title:'Gym — upper body',sub:'Personal · 60 minutes',type:'Personal',done:false}
]);
let thoughts=store.get('tide_thoughts',[
 {text:'Follow up with Neha for pending payment',meta:'Follow-up · Tomorrow',icon:'↗'},
 {text:'Ask Aman to prepare five reel concepts',meta:'Team task · Today',icon:'♙'},
 {text:'Carry Aadhaar copy for BMC file',meta:'Reminder · Today 2:00 PM',icon:'□'},
 {text:'Book dinner with college friends',meta:'Personal · This weekend',icon:'♡'}
]);
let people=[
 {name:'Rohan Mehta',type:'Lead',note:'Interested in social media management.',next:'Follow up today',hot:true},
 {name:'Aman Shaikh',type:'Team',note:'Intern · Video and reels',next:'2 tasks pending'},
 {name:'Neha Kapoor',type:'Client',note:'Brand campaign · Payment follow-up',next:'Call tomorrow'},
 {name:'Sahil Patil',type:'Team',note:'Intern · Content and research',next:'1 task pending'},
 {name:'Mr. Deshmukh',type:'Client',note:'BMC plumbing file contact',next:'Visit Friday'},
 {name:'Cafe Monsoon',type:'Client',note:'Social media and content strategy',next:'Meeting 12:30 PM'}
];
let rules=store.get('tide_rules',[
 'No WhatsApp before my first important task is complete.',
 'If it takes less than two minutes, do it now.',
 'Never end a meeting without deciding the next step.',
 'Work ends at 8:30 PM unless it is genuinely urgent.',
 'One clean meal is better than a perfect plan tomorrow.'
]);
const routine=[
 ['7:30','☀','Wake up','Water · No phone for 20 min'],['8:00','◎','Plan the day','Arrange your task queue'],['9:00','→','Deep work','Most important business task'],['1:30','♨','Lunch & reset','Clean meal · 20 min break'],['6:30','⌁','Gym / movement','60 minutes'],['10:45','☾','Slow down','Review day · Plan tomorrow'],['11:30','·','Phone away','Sleep target: 12:00 AM']
];
let meetings=store.get('tide_meetings',[
 {time:'10:30 AM',title:'Call Rohan',day:'Today',sub:'Campaign proposal · Phone',kind:''},
 {time:'12:30 PM',title:'Content strategy review',day:'Today',sub:'Cafe Monsoon · Google Meet',kind:''},
 {time:'2:15 PM',title:'BMC Ward Office visit',day:'Today',sub:'File PL-284 · Andheri East',kind:'orange'},
 {time:'5:00 PM',title:'Intern check-in',day:'Today',sub:'Office · 20 minutes',kind:''}
]);
let routineLogs=store.get('tide_routine_logs',[
 {id:'r1',category:'Food',icon:'♨',text:'1 burger',value:520,unit:'kcal',time:'1:15 PM',detail:'Estimated food energy'},
 {id:'r2',category:'Water',icon:'≈',text:'500 ml water',value:500,unit:'ml',time:'10:40 AM',detail:'Hydration'},
 {id:'r3',category:'Workout',icon:'⌁',text:'45 minutes gym workout',value:320,unit:'kcal burned',time:'7:10 AM',detail:'45 min · moderate'},
 {id:'r4',category:'Sleep',icon:'☾',text:'Night sleep',value:7.2,unit:'hours',time:'7:30 AM',detail:'Good recovery'},
 {id:'r5',category:'Work',icon:'→',text:'Client proposal focus',value:2,unit:'hours',time:'11:00 AM',detail:'Focused work'}
]);
let routineSchedule=store.get('tide_routine_schedule',[
 {time:'7:30 AM',icon:'☀',title:'Wake up & water',days:'Every day',category:'Wellness'},
 {time:'8:00 AM',icon:'♨',title:'Clean breakfast',days:'Mon–Sat',category:'Food'},
 {time:'9:00 AM',icon:'→',title:'Deep work block',days:'Mon–Fri',category:'Work'},
 {time:'6:30 PM',icon:'⌁',title:'Gym / movement',days:'Mon, Wed, Fri',category:'Workout'},
 {time:'11:30 PM',icon:'☾',title:'Phone away',days:'Every day',category:'Sleep'}
]);
let currentTheme=store.get('tide_theme','light');
function applyTheme(theme){currentTheme=theme;document.body.classList.toggle('dark-theme',theme==='dark');$('#themeToggle').textContent=theme==='dark'?'☀':'◐';store.set('tide_theme',theme)}
let activeTab='today',tabHistory=['today'],handlingPop=false;
function showTab(id){activeTab=id;$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));window.scrollTo({top:0,behavior:'smooth'})}
function switchTab(id){if(id===activeTab)return;tabHistory.push(id);showTab(id);if(!handlingPop)history.pushState({tab:id},'',`#${id}`)}
history.replaceState({tab:'today'},'',location.pathname+location.search+'#today');window.onpopstate=e=>{handlingPop=true;let tab=e.state?.tab||'today';showTab(tab);handlingPop=false};
$$('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$$('[data-open-dump]').forEach(b=>b.onclick=()=>{switchTab('dump');setTimeout(()=>$('#dumpInput').focus(),100)});
const greetingSeed=Math.floor(Math.random()*10000);
function updateGreeting(){let now=new Date(),h=now.getHours(),main,subtitle,lines;if(h>=5&&h<12){main='Good morning,';subtitle='Here’s what deserves your attention today.';lines=['One clear task at a time.','Start calm. Finish strong.','Small steps, real progress.','Protect your first hour.']}else if(h>=12&&h<17){main='Good afternoon,';subtitle='Here’s what deserves your attention next.';lines=['Keep the momentum steady.','Do the next right thing.','Stay focused, not rushed.','Progress over pressure.']}else if(h>=17&&h<22){main='Good evening,';subtitle='';lines=['Finish the day well.','Close the important loops.','A little progress still counts.','End with a clear mind.']}else{main='Good night,';subtitle='Finish the right things, then give yourself time to rest.';lines=['Wrap up, then rest.','Tomorrow needs your energy.','Finish gently. Rest properly.','One last task, then switch off.']}let message=lines[greetingSeed%lines.length];$('#greetingMain').textContent=main;$('#greetingMessage').textContent=message;$('#greetingSubtitle').textContent=subtitle;$('#greetingSubtitle').style.display=subtitle?'block':'none';let full=now.toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'});$('#dailyDateLabel').textContent='DAILY UPDATE · '+full.toUpperCase();$('#liveDate').textContent=full;$('#routineDateLabel').textContent=full}
function localISO(d=new Date()){let x=new Date(d);return[x.getFullYear(),String(x.getMonth()+1).padStart(2,'0'),String(x.getDate()).padStart(2,'0')].join('-')}
function currentTimeText(d=new Date()){return new Date(d).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'})}
function ensureMeetingTasks(){let changed=false;meetings.forEach(m=>{let date=meetingDateISO(m);if(!tasks.some(t=>t.title.toLowerCase()===m.title.toLowerCase()&&taskDateISO(t)===date)){tasks.push({id:'task-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,5),title:m.title,time:m.time||currentTimeText(),date,day:m.day||dateLabel(date),type:'Work',category:'Meeting',sub:m.sub||'Meeting',done:false});changed=true}});if(changed)store.set('tide_tasks',tasks)}
function normalizeTaskTimes(){let changed=false;tasks.forEach(t=>{if(!t.time||t.time==='Any time'){t.time=t.createdAt||currentTimeText();changed=true}if(!t.createdAt){t.createdAt=t.time;changed=true}});if(changed)store.set('tide_tasks',tasks)}
function rollOverPendingTasks(){let today=localISO(),changed=false;tasks.forEach(t=>{let due=taskDateISO(t);if(!t.done&&due<today){if(!t.pendingSince)t.pendingSince=due;t.originalDate=t.originalDate||due;t.date=today;t.day='Today';t.sub=`Pending from ${t.pendingSince} · ${taskCategory(t)}`;changed=true}});if(changed)store.set('tide_tasks',tasks);return changed}
function taskDateISO(t){if(t.date)return t.date;let base=new Date(),day=(t.day||'Today').toLowerCase();if(day==='tomorrow')base.setDate(base.getDate()+1);else if(day!=='today'){let names=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],target=names.indexOf(day);if(target>=0){let add=(target-base.getDay()+7)%7||7;base.setDate(base.getDate()+add)}}return localISO(base)}
function dateHeading(date){let d=new Date(date+'T00:00:00'),today=localISO(),tom=new Date();tom.setDate(tom.getDate()+1);let prefix=date===today?'Today':date===localISO(tom)?'Tomorrow':d.toLocaleDateString('en-IN',{weekday:'long'});return`${prefix} · ${d.toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}`}
let selectedQueueDate=localISO();
function currentTaskIndex(){let today=localISO();return tasks.findIndex(t=>!t.done&&taskDateISO(t)===today)}
function updateNextTask(){let today=localISO(),todayTasks=tasks.filter(t=>!t.done&&taskDateISO(t)===today),i=currentTaskIndex(),t=tasks[i],count=todayTasks.length,card=$('#nextCard');card.classList.remove('level-blue','level-yellow','level-orange','level-red');card.classList.add(count>=15?'level-red':count>=10?'level-orange':count>=7?'level-yellow':'level-blue');$('#todayTaskCount').textContent=`${count} ${count===1?'TASK':'TASKS'} TODAY`;if(!t){$('#nextTaskTitle').textContent='You’re clear for today';$('#nextTaskMeta').innerHTML='<span class="tag client">Open your list or choose another date</span>';return}$('#nextTaskTitle').textContent=t.title;$('#nextTaskMeta').innerHTML=`<span class="tag client">${taskCategory(t)}</span><span>◷ ${t.time}</span>${t.client?`<span>♙ ${escapeHtml(t.client)}</span>`:''}${t.pendingSince?`<span class="tag client">Pending from ${new Date(t.pendingSince+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span>`:''}`}
function renderTasks(){ensureTaskIds();updateNextTask();if($('.category-dashboard'))renderTodayCards();if($('#monthTaskFeed'))renderMonthFeed(monthFeedOffset);if($('#meetingsPageList'))renderDedicatedPages()}
function completeCurrentTask(){let i=currentTaskIndex();if(i<0)return;let finished=tasks[i].title;tasks[i].done=true;tasks[i].completedAt=new Date().toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'});store.set('tide_tasks',tasks);renderTasks();toast(`Done: ${finished}. Next task loaded.`)}
function ensureTaskIds(){let changed=false;tasks.forEach((t,i)=>{if(!t.id){t.id='task-'+Date.now().toString(36)+'-'+i+'-'+Math.random().toString(36).slice(2,6);changed=true}});if(changed)store.set('tide_tasks',tasks)}
function openTaskQueue(date=selectedQueueDate){
 selectedQueueDate=date||localISO();ensureTaskIds();let queue=tasks.filter(t=>!t.done&&taskDateISO(t)===selectedQueueDate),completed=tasks.filter(t=>t.done&&taskDateISO(t)===selectedQueueDate),count=queue.length,level=count>=15?'red':count>=10?'orange':count>=7?'yellow':'blue',dayText=count>=15?'Heavy day':count>=10?'Busy day':count>=7?'Balanced day':'Light day';$('#modalBody').innerHTML=`<div class="queue-date-head"><div><h2>To Do List</h2><p>${dateHeading(selectedQueueDate)}</p></div><div class="queue-head-actions"><span class="queue-load ${level}">${dayText}</span><label class="queue-calendar" title="Choose date"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M8 3v4M16 3v4M3 10h18"/><path d="M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01"/></svg><input id="queueDatePicker" type="date" value="${selectedQueueDate}"></label><button class="queue-head-add" id="queueHeadAdd" title="Add task">＋</button></div></div><div class="queue-section-title"><strong>Pending tasks</strong><span>${dateHeading(selectedQueueDate)}</span></div><div class="queue-list" id="queueList">${queue.map((t,pos)=>`<div class="queue-item ${pos===0?'current':''}" data-task-id="${t.id}"><span class="queue-number">${pos+1}.</span><div class="queue-task-text" data-edit-task="${t.id}"><strong>${pos===0&&selectedQueueDate===localISO()?'Now · ':''}${escapeHtml(t.title)}</strong><small>${t.pendingSince?pendingStatus(t):`${t.time} · ${taskCategory(t)}`}</small></div><span class="queue-handle" title="Drag">☷</span><button class="queue-check" data-complete-queue="${t.id}" aria-label="Complete task"></button></div>`).join('')||'<div class="summary-box">Nothing pending for this date. Use ＋ to add a task.</div>'}</div><div class="completed-column"><div class="completed-column-head"><strong>Tasks completed</strong><span>${completed.length}</span></div>${completed.length?completed.map((t,i)=>`<div class="completed-task"><span>${i+1}.</span><div class="queue-task-text" data-edit-task="${t.id}"><strong>${escapeHtml(t.title)}</strong><small>${t.time}${t.completedAt?' · Completed '+t.completedAt:''}</small></div><button class="queue-check checked" data-restore-task="${t.id}" aria-label="Restore task">✓</button></div>`).join(''):'<div class="completed-task"><span>—</span><div><strong style="text-decoration:none">No tasks completed</strong><small>Finished tasks for this date will appear here.</small></div><span></span></div>'}</div>`;$('#modal').classList.add('open');
 $('#queueDatePicker').onchange=e=>openTaskQueue(e.target.value);bindFastTap($('#queueHeadAdd'),()=>openQuickAddTask(selectedQueueDate));$$('[data-complete-queue]').forEach(b=>bindFastTap(b,()=>completeQueueTask(b.dataset.completeQueue,b)));$$('[data-restore-task]').forEach(b=>bindFastTap(b,()=>restoreQueueTask(b.dataset.restoreTask)));$$('[data-edit-task]').forEach(x=>x.onclick=()=>{let i=tasks.findIndex(t=>t.id===x.dataset.editTask);if(i>=0)openTaskActions(i)});setupSmoothQueueDrag();
}
function syncAfterQueueChange(){updateNextTask();if($('.category-dashboard'))renderTodayCards();openTaskQueue(selectedQueueDate);setTimeout(()=>{if($('#monthTaskFeed'))renderMonthFeed(monthFeedOffset);if($('#meetingsPageList'))renderDedicatedPages();if(activeTab==='calendar'){renderCalendar(weekOffset);if(currentCalendarView!=='daily')renderCalendarOverview(currentCalendarView)}},40)}
function completeQueueTask(id,button){let item=button.closest('.queue-item'),task=tasks.find(t=>t.id===id);if(!task)return;button.classList.add('checked');button.textContent='✓';item.classList.add('completing');task.done=true;task.completedAt=currentTimeText();store.set('tide_tasks',tasks);setTimeout(()=>{syncAfterQueueChange();toast('Task completed and moved below.')},70)}
function restoreQueueTask(id){let task=tasks.find(t=>t.id===id);if(!task)return;task.done=false;delete task.completedAt;moveReopenedTaskToToday(task);store.set('tide_tasks',tasks);selectedQueueDate=taskDateISO(task);syncAfterQueueChange();toast(task.pendingSince?'Moved to Today · Pending from '+new Date(task.pendingSince+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'Task moved back to pending.')}
function openEditTask(id,returnDate=taskDateISO(tasks.find(t=>t.id===id)||{})){let task=tasks.find(t=>t.id===id);if(!task)return;modal('Edit task','Change the task text and save it everywhere.',`<div class="form-field"><label>TASK TEXT</label><input id="editTaskTitle" value="${escapeHtml(task.title)}"></div>`,()=>{let title=$('#editTaskTitle').value.trim();if(!title)return toast('Task text cannot be empty.');task.title=title;store.set('tide_tasks',tasks);renderTasks();renderCalendar(weekOffset);toast('Task updated everywhere.');openTaskQueue(returnDate)});setTimeout(()=>{$('#editTaskTitle').focus();$('#editTaskTitle').select()},50)}
function saveQueueOrder(){let ids=$$('.queue-item',$('#queueList')).map(el=>el.dataset.taskId),ordered=ids.map(id=>tasks.find(t=>t.id===id)).filter(Boolean),n=0;tasks=tasks.map(t=>(!t.done&&taskDateISO(t)===selectedQueueDate)?ordered[n++]:t);store.set('tide_tasks',tasks);renderTasks()}
function renumberQueue(){ $$('.queue-item',$('#queueList')).forEach((el,i)=>{el.querySelector('.queue-number').textContent=(i+1)+'.';el.classList.toggle('current',i===0);let strong=el.querySelector('strong');strong.textContent=strong.textContent.replace(/^Now · /,'');if(i===0)strong.textContent='Now · '+strong.textContent}) }
function setupSmoothQueueDrag(){let list=$('#queueList'),scroller=$('.modal-card'),dragged=null;function finishDrag(){if(!dragged)return;$$('.queue-item.dragging',list).forEach(x=>x.classList.remove('dragging'));dragged=null;saveQueueOrder()}
 $$('.queue-item',list).forEach(item=>{let handle=item.querySelector('.queue-handle');handle.onpointerdown=e=>{e.preventDefault();dragged=item;handle.setPointerCapture?.(e.pointerId)};handle.onpointermove=e=>{if(!dragged)return;let sr=scroller.getBoundingClientRect();if(e.clientY>sr.bottom-55)scroller.scrollTop+=14;else if(e.clientY<sr.top+55)scroller.scrollTop-=14;let target=document.elementFromPoint(e.clientX,e.clientY)?.closest('.queue-item');if(!target||target===dragged||target.parentElement!==list)return;let box=target.getBoundingClientRect(),before=e.clientY<box.top+box.height/2;if((before&&dragged.nextElementSibling===target)||(!before&&target.nextElementSibling===dragged))return;list.insertBefore(dragged,before?target:target.nextSibling);renumberQueue()};handle.onpointerup=handle.onpointercancel=handle.onlostpointercapture=finishDrag})
}
function openQuickAddTask(defaultDate=selectedQueueDate){let now=new Date(),currentTime=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;modal('Add another task','Date and time are already set to now. Change only if needed.',`<div class="quick-title-row"><div class="form-field"><label>WHAT NEEDS TO BE DONE?</label><input id="quickTaskTitle" placeholder="Write or speak your task"></div><button type="button" class="icon-btn" id="quickTaskVoice" title="Voice type">●</button></div><div class="quick-fields-row"><div class="form-field"><label>DATE</label><input id="quickTaskDate" type="date" value="${defaultDate||localISO()}"></div><div class="form-field"><label>TIME</label><input id="quickTaskTime" type="time" value="${currentTime}"></div><div class="form-field"><label>TYPE</label><select id="quickTaskType"><option>Task</option><option>Meeting</option><option>Reminder</option><option>Follow-up</option></select></div></div>`,()=>{let title=$('#quickTaskTitle').value.trim();if(!title)return toast('Write or speak the task first.');let raw=$('#quickTaskTime').value,date=$('#quickTaskDate').value,time=new Date('2026-01-01T'+raw).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),category=$('#quickTaskType').value,day=dateLabel(date),type=category==='Reminder'?'Personal':'Work';let newTask={id:'task-'+Date.now().toString(36),title,time,createdAt:currentTimeText(),date,day,type,category,sub:`${day} · ${category}`,done:false};tasks.push(newTask);if(category==='Meeting'){meetings.push({title,time,date,day,sub:'Added from To Do List',kind:''});store.set('tide_meetings',meetings)}store.set('tide_tasks',tasks);renderTasks();$('#modal').classList.remove('open');toast('Task added to your list.')});$('#quickTaskVoice').onclick=()=>{voiceMode='quickTask';openVoice()};setTimeout(()=>$('#quickTaskTitle').focus(),50)}
function pendingStatus(t){if(t.done)return`Completed${t.completedAt?' at '+t.completedAt:''}`;if(!t.pendingSince)return taskCategory(t);let start=new Date(t.pendingSince+'T00:00:00'),now=new Date(localISO()+'T00:00:00'),days=Math.max(1,Math.round((now-start)/86400000));return`Pending from ${start.toLocaleDateString('en-IN',{day:'numeric',month:'short'})} · ${days} ${days===1?'day':'days'}`}
function openTaskActions(i){let t=tasks[i];$('#modalBody').innerHTML=`<h2>${escapeHtml(t.title)}</h2><p>${pendingStatus(t)}</p><div class="action-list"><button data-task-action="edit">✎ Edit task</button><button data-task-action="done">${t.done?'↩ Move back to pending':'✓ Mark complete'}</button><button data-task-action="tomorrow">→ Move to tomorrow</button><button class="danger" data-task-action="remove">× Delete task</button></div>`;$('#modal').classList.add('open');$$('[data-task-action]').forEach(b=>b.onclick=()=>{let a=b.dataset.taskAction;if(a==='edit'){openEditTask(t.id,selectedQueueDate)}else if(a==='done'){t.done=!t.done;if(t.done)t.completedAt=currentTimeText();else delete t.completedAt;finishTaskAction(t.done?'Completed everywhere.':'Moved back to pending.')}else if(a==='tomorrow'){let d=new Date();d.setDate(d.getDate()+1);t.date=localISO(d);t.day='Tomorrow';delete t.pendingSince;finishTaskAction('Moved to tomorrow.')}else if(a==='remove'){tasks.splice(i,1);finishTaskAction('Task deleted.')}})}
function finishTaskAction(msg){store.set('tide_tasks',tasks);renderTasks();$('#modal').classList.remove('open');toast(msg)}
function scheduleReminder(t,minutes){if('Notification'in window&&Notification.permission==='granted')setTimeout(()=>new Notification('Tide reminder',{body:t.title}),Math.min(minutes*60000,2147483647));}
function openTaskDetails(i){let t=tasks[i];if(t.type==='BMC')return openBmcChecklist(t);if(t.type==='Team')return openStaffTask(i);$('#modalBody').innerHTML=`<h2>${escapeHtml(t.title)}</h2><p>Keep the next action simple.</p><div class="summary-box"><strong>${t.type}</strong><br>${t.time} · ${t.sub}</div><div class="action-list"><button id="callAction">☎ Call person</button><button id="whatsappAction">◉ Open WhatsApp</button><button id="copyAction">□ Copy follow-up message</button></div>`;$('#callAction').onclick=()=>toast('Add the contact number in People to call.');$('#whatsappAction').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent('Hi, following up regarding '+t.title),'_blank');$('#copyAction').onclick=()=>{navigator.clipboard?.writeText('Hi, just following up regarding '+t.title+'. Please let me know the next step.');toast('Follow-up message copied.')};}
function openStaffTask(i){let t=tasks[i];$('#modalBody').innerHTML=`<h2>${escapeHtml(t.title)}</h2><p>Only four simple stages.</p><div class="action-list">${['Assigned','In progress','Submitted','Approved'].map(s=>`<button data-status="${s}">${t.status===s?'✓ ':''}${s}</button>`).join('')}</div>`;$$('[data-status]').forEach(b=>b.onclick=()=>{t.status=b.dataset.status;store.set('tide_tasks',tasks);renderTasks();$('#modal').classList.remove('open');toast('Staff task updated → '+t.status)})}
function renderThoughts(){
 $('#thoughtCount').textContent=`${thoughts.length} items`;
 $('#thoughtList').innerHTML=thoughts.map((t,i)=>`<div class="thought"><span class="thought-icon">${t.icon}</span><div><strong>${escapeHtml(t.text)}</strong><small>${t.meta}</small></div><button data-del-thought="${i}">×</button></div>`).join('')||'<div class="thought"><div><strong>Your mind is clear.</strong><small>Add anything that comes up.</small></div></div>';
 $$('[data-del-thought]').forEach(b=>b.onclick=()=>{thoughts.splice(+b.dataset.delThought,1);store.set('tide_thoughts',thoughts);renderThoughts()});
}
function classify(text){let low=text.toLowerCase();if(/meet|meeting|appointment|schedule/.test(low))return ['Meeting','↗'];if(/intern|aman|sahil|assign|team|staff/.test(low))return ['Team task','♙'];if(/bmc|plumb|file|ward|municipal/.test(low))return ['BMC reminder','□'];if(/gym|workout|food|meal|dinner|sleep|wake|personal|doctor/.test(low))return ['Personal','♡'];if(/call|follow[ -]?up|client|payment|proposal|lead/.test(low))return ['Follow-up','↗'];return ['Task · Inbox','✦']}
function getTime(text){
 let m=text.match(/\b(?:at|by)\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b/i);if(!m)return currentTimeText();
 let h=+m[1],min=m[2]||'00',ap=(m[3]||'').toUpperCase();if(!ap)ap=h>=8&&h<=11?'AM':'PM';if(h>12)h-=12;return `${h}:${min} ${ap}`;
}
function getDay(text){let l=text.toLowerCase();if(l.includes('tomorrow'))return 'Tomorrow';if(l.includes('today'))return 'Today';let d=l.match(/\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/);return d?d[1][0].toUpperCase()+d[1].slice(1):'Today'}
function routeCapture(text){
 let [kind,icon]=classify(text),time=getTime(text),day=getDay(text),destination='To Do List';
 thoughts.unshift({text,meta:`Just now · ${kind}`,icon});store.set('tide_thoughts',thoughts);renderThoughts();
 if(kind==='Meeting'){meetings.unshift({time,title:text,day,sub:`${day} · Added automatically`,kind:''});store.set('tide_meetings',meetings);renderCalendar(weekOffset);destination='Calendar + To Do List'}
 let type=kind==='Team task'?'Team':kind==='BMC reminder'?'BMC':kind==='Personal'?'Personal':'Work',category=kind==='Meeting'?'Meeting':kind==='BMC reminder'||kind==='Personal'?'Reminder':kind==='Follow-up'?'Follow-up':'Task';tasks.unshift({id:'task-'+Date.now().toString(36),time,createdAt:currentTimeText(),title:text,day,sub:`${day} · ${kind}`,type,category,done:false,status:type==='Team'?'Assigned':''});store.set('tide_tasks',tasks);renderTasks();
 return {kind,time,day,destination};
}
function saveThought(){let input=$('#dumpInput'),text=input.value.trim();if(!text)return toast('Write anything first — even a few words.');let result=routeCapture(text);input.value='';toast(`Organised automatically → ${result.destination}`);}
$('#saveDump').onclick=saveThought;$('#dumpInput').addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='Enter')saveThought()});
$$('.prompt').forEach(b=>b.onclick=()=>{$('#dumpInput').value=b.textContent;$('#dumpInput').focus()});
$('#toggleManualForm').onclick=()=>{let box=$('.manual-entry');box.classList.toggle('open');$('#toggleManualForm').textContent=box.classList.contains('open')?'− Hide form':'＋ Add detailed item';if(box.classList.contains('open'))setTimeout(()=>$('#manualTitle').focus(),80)};
function dateLabel(value){if(!value)return'Today';let d=new Date(value+'T00:00:00'),now=new Date(),tom=new Date();tom.setDate(now.getDate()+1);if(d.toDateString()===now.toDateString())return'Today';if(d.toDateString()===tom.toDateString())return'Tomorrow';return d.toLocaleDateString('en-IN',{weekday:'long'})}
$('#manualTaskForm').onsubmit=e=>{e.preventDefault();let itemType=$('#manualType').value,title=$('#manualTitle').value.trim(),date=$('#manualDate').value,timeValue=$('#manualTime').value;if(!title||!date)return toast('Add a name and date first.');let day=dateLabel(date),time=timeValue?new Date('2026-01-01T'+timeValue).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}):currentTimeText(),client=$('#manualClient').value.trim(),service=$('#manualService').value.trim(),assignee=$('#manualAssignee').value,notes=$('#manualNotes').value.trim(),details={time,title,day,date,client,service,assignee,notes,sub:`${day} · ${itemType}`};
 if(itemType==='Meeting'){meetings.unshift({...details,kind:''});store.set('tide_meetings',meetings)}let type=itemType==='BMC work'?'BMC':itemType==='Team task'?'Team':itemType==='Personal'?'Personal':'Work',category=itemType==='Meeting'?'Meeting':itemType==='Client follow-up'?'Follow-up':itemType==='BMC work'||itemType==='Personal'?'Reminder':'Task';tasks.unshift({...details,id:'task-'+Date.now().toString(36),type,category,done:false,status:type==='Team'?'Assigned':''});store.set('tide_tasks',tasks);renderTasks()
 if(client&&!people.some(p=>p.name.toLowerCase()===client.toLowerCase())){people.unshift({name:client,type:'Client',note:service||'Added from detailed task',next:day+' · '+time});renderPeople()}
 thoughts.unshift({text:title,meta:`Detailed ${itemType} · ${day}`,icon:itemType==='Meeting'?'↗':'□'});store.set('tide_thoughts',thoughts);renderThoughts();renderCalendar(weekOffset);e.target.reset();setManualDate();$('.manual-entry').classList.remove('open');$('#toggleManualForm').textContent='＋ Add detailed item';toast(`${itemType} saved with full details.`)};
function setManualDate(){let d=new Date();$('#manualDate').value=localISO(d);$('#manualTime').value=`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
// Voice capture: speak naturally, then the app classifies and routes it without a form.
let recognition=null,voiceSaved=false,voiceMode='capture';
function closeVoice(){if(recognition)try{recognition.stop()}catch{};$('#voiceOverlay').classList.remove('open');voiceMode='capture'}
function showVoiceResult(text){if(!text||voiceSaved)return;text=text.replace(/^\s*brain[,:]?\s*/i,'').trim()||text;voiceSaved=true;$('#voiceTranscript').textContent=text;if(voiceMode==='quickTask'){let field=$('#quickTaskTitle');if(field)field.value=text.trim();$('#voiceStatus').textContent='Task typed';$('#voiceHint').textContent='Close this and confirm the date, time and type.';$('#voiceResult').innerHTML='<strong>Added to task field</strong><br>'+escapeHtml(text.trim());$('#voiceResult').classList.add('show');$('.voice-done').style.display='block';return}if(voiceMode==='routine'){let entry=trackRoutineEntry(text.trim());$('#voiceStatus').textContent='Routine tracked';$('#voiceHint').textContent='AI sorted your update automatically.';$('#voiceResult').innerHTML=`<strong>${entry.category}</strong><br>${entry.value} ${entry.unit} · ${entry.detail}`;$('#voiceResult').classList.add('show');$('.voice-done').style.display='block';return}showVoiceDraft(text.trim())}
let voiceDraftCategory='Task';
function spokenDateISO(text){let l=text.toLowerCase(),d=new Date();if(l.includes('tomorrow'))d.setDate(d.getDate()+1);else{let names=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],target=names.findIndex(n=>l.includes(n));if(target>=0){let add=(target-d.getDay()+7)%7||7;d.setDate(d.getDate()+add)}}return localISO(d)}
function detectedVoiceCategory(text){let [kind]=classify(text);return kind==='Meeting'?'Meeting':kind==='BMC reminder'||kind==='Personal'?'Reminder':kind==='Follow-up'?'Follow-up':'Task'}
function showVoiceDraft(text){voiceDraftCategory=detectedVoiceCategory(text);let date=spokenDateISO(text),time=getTime(text),raw=time.match(/(\d{1,2}):(\d{2})\s*(AM|PM)/i),hour=raw?+raw[1]:new Date().getHours(),min=raw?raw[2]:String(new Date().getMinutes()).padStart(2,'0');if(raw&&raw[3].toUpperCase()==='PM'&&hour<12)hour+=12;if(raw&&raw[3].toUpperCase()==='AM'&&hour===12)hour=0;let time24=`${String(hour).padStart(2,'0')}:${min}`;$('#voiceStatus').textContent='Review before saving';$('#voiceHint').textContent='Edit any mistake, then choose where it belongs.';$('#voiceResult').innerHTML=`<div class="voice-review"><input id="voiceDraftText" value="${escapeHtml(text)}"><div class="voice-category-row">${[['Meeting','📅'],['Reminder','🔔'],['Follow-up','📞'],['Task','✅']].map(([c,e])=>`<button class="${c===voiceDraftCategory?'active':''}" data-voice-category="${c}">${e}<span>${c}</span></button>`).join('')}</div><div class="voice-date-row"><label>Date<input id="voiceDraftDate" type="date" value="${date}"></label><label>Time<input id="voiceDraftTime" type="time" value="${time24}"></label></div><button class="primary" id="saveVoiceDraft">Save to To Do List</button></div>`;$('#voiceResult').classList.add('show');$('.voice-done').style.display='none';$$('[data-voice-category]').forEach(b=>b.onclick=()=>{voiceDraftCategory=b.dataset.voiceCategory;$$('[data-voice-category]').forEach(x=>x.classList.toggle('active',x===b))});$('#saveVoiceDraft').onclick=saveReviewedVoiceTask}
function saveReviewedVoiceTask(){let title=$('#voiceDraftText').value.trim(),date=$('#voiceDraftDate').value,raw=$('#voiceDraftTime').value;if(!title)return toast('Write the task first.');let time=new Date('2026-01-01T'+raw).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),type=voiceDraftCategory==='Reminder'?'Personal':'Work',task={id:'task-'+Date.now().toString(36),title,date,day:dateLabel(date),time,createdAt:currentTimeText(),type,category:voiceDraftCategory,sub:`Voice · ${voiceDraftCategory}`,done:false};tasks.unshift(task);if(voiceDraftCategory==='Meeting'){meetings.unshift({title,date,day:task.day,time,sub:'Added by voice',kind:''});store.set('tide_meetings',meetings)}thoughts.unshift({text:title,meta:`Voice · ${voiceDraftCategory}`,icon:'✦'});store.set('tide_tasks',tasks);store.set('tide_thoughts',thoughts);renderTasks();renderThoughts();renderCalendar(weekOffset);$('#voiceStatus').textContent='Saved';$('#voiceHint').textContent='Added everywhere automatically.';$('#voiceResult').innerHTML=`<strong>${voiceDraftCategory}</strong><br>${escapeHtml(title)} · ${date} · ${time}`;$('.voice-done').style.display='block';toast('Voice task saved and connected.')}
window.handleNativeVoice=showVoiceResult;window.handleNativeVoiceError=msg=>{$('#voiceStatus').textContent='I couldn’t hear that';$('#voiceTranscript').textContent=msg||'Please try speaking again.';$('.voice-done').style.display='block'};
function openVoice(){
 const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 $('#voiceOverlay').classList.add('open');$('#voiceStatus').textContent='What’s on your mind?';$('#voiceHint').textContent='Speak naturally. I’ll organise it for you.';$('#voiceTranscript').textContent='Listening…';$('#voiceResult').classList.remove('show');$('.voice-done').style.display='none';voiceSaved=false;
 if(window.AndroidVoice){window.AndroidVoice.startListening();return}
 if(!SpeechRecognition){$('#voiceStatus').textContent='Voice is not supported here';$('#voiceTranscript').textContent='Open this app in Chrome or Edge, or type in Brain Dump.';$('.voice-done').style.display='block';return}
 recognition=new SpeechRecognition();recognition.lang='en-IN';recognition.interimResults=true;recognition.continuous=false;
 recognition.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)final+=e.results[i][0].transcript;else interim+=e.results[i][0].transcript}$('#voiceTranscript').textContent=final||interim;if(final)showVoiceResult(final)};
 recognition.onerror=e=>{if(e.error==='not-allowed')$('#voiceTranscript').textContent='Please allow microphone access and try again.';else $('#voiceTranscript').textContent='I couldn’t hear that. Tap Speak and try again.';$('.voice-done').style.display='block'};
 recognition.onend=()=>{if(!voiceSaved){$('#voiceStatus').textContent='I didn’t catch that';$('#voiceHint').textContent='Close and tap Speak to try once more.';$('.voice-done').style.display='block'}};
 try{recognition.start()}catch{}
}
$('#voiceBtn').onclick=()=>{voiceMode='capture';openVoice()};$('#globalVoice').onclick=()=>{voiceMode='capture';openVoice()};$('#routineVoiceBtn').onclick=()=>{voiceMode='routine';openVoice()};bindFastTap($('#voiceClose'),closeVoice);$('#voiceDone').onclick=closeVoice;
let wakeModeActive=false,wakeRecognition=null,wakeArmed=false;
function stopBrainWakeMode(){wakeModeActive=false;wakeArmed=false;try{wakeRecognition?.stop()}catch{};$('#brainWakeToggle').classList.remove('active');$('#brainWakeToggle').textContent='◉ “Brain” wake mode'}
function toggleBrainWakeMode(){if(wakeModeActive)return stopBrainWakeMode();const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){if(window.AndroidVoice){voiceMode='capture';openVoice();toast('Say “Brain” followed by your task. Continuous wake mode needs the native upgrade.')}else toast('Wake mode needs Chrome microphone support.');return}wakeModeActive=true;$('#brainWakeToggle').classList.add('active');$('#brainWakeToggle').textContent='● Listening for “Brain”';wakeRecognition=new SR();wakeRecognition.lang='en-IN';wakeRecognition.continuous=true;wakeRecognition.interimResults=false;wakeRecognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(!e.results[i].isFinal)continue;let speech=e.results[i][0].transcript.trim(),lower=speech.toLowerCase(),at=lower.indexOf('brain');if(at>=0){let after=speech.slice(at+5).trim();if(after){voiceMode='capture';voiceSaved=false;$('#voiceOverlay').classList.add('open');$('#voiceTranscript').textContent=after;showVoiceResult(after);wakeArmed=false}else{wakeArmed=true;toast('Listening—tell Brain what to add.')}}else if(wakeArmed){voiceMode='capture';voiceSaved=false;$('#voiceOverlay').classList.add('open');showVoiceResult(speech);wakeArmed=false}}};wakeRecognition.onerror=e=>{if(e.error==='not-allowed'){stopBrainWakeMode();toast('Allow microphone access to use Brain wake mode.')}};wakeRecognition.onend=()=>{if(wakeModeActive)setTimeout(()=>{try{wakeRecognition.start()}catch{}},350)};try{wakeRecognition.start();toast('Brain wake mode is listening while this app stays open.')}catch{stopBrainWakeMode()}}
$('#brainWakeToggle').onclick=toggleBrainWakeMode;
function renderPeople(filter='all',query=''){let list=people.map((p,i)=>({...p,_i:i})).filter(p=>(filter==='all'||p.type===filter)&&p.name.toLowerCase().includes(query.toLowerCase()));$('#peopleGrid').innerHTML=list.map(p=>`<div class="person-card" data-person="${p._i}"><div class="person-top"><div class="person-avatar">${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h4>${p.name}</h4><span>${p.type}</span></div></div><p class="person-note">${p.note}</p><div class="person-foot"><span>Next follow-up</span><b>${p.next}</b></div></div>`).join('');$$('[data-person]').forEach(c=>c.onclick=()=>openPerson(+c.dataset.person))}
function openPerson(i){
 let p=people[i],first=p.name.split(' ')[0].toLowerCase(),assigned=tasks.map((t,ti)=>({...t,_i:ti})).filter(t=>t.type==='Team'&&t.title.toLowerCase().includes(first));
 let teamView=p.type==='Team'?`<div class="small-label">ASSIGNED WORK</div><div class="action-list">${assigned.length?assigned.map(t=>`<button data-open-team-task="${t._i}"><strong>${escapeHtml(t.title)}</strong><br><small>${t.status||'Assigned'} · ${t.time}</small></button>`).join(''):'<button>No assigned tasks yet</button>'}</div>`:`<div class="form-field"><label>NEXT FOLLOW-UP</label><input id="nextFollowup" value="${p.next}"></div><div class="action-list"><button id="saveFollowup">✓ Save next follow-up</button><button id="personCall">☎ Call</button><button id="personWhatsapp">◉ Open WhatsApp</button><button id="personCopy">□ Copy follow-up message</button></div>`;
 $('#modalBody').innerHTML=`<h2>${p.name}</h2><p>${p.type} · ${p.note}</p>${teamView}`;$('#modal').classList.add('open');
 if(p.type==='Team'){$$('[data-open-team-task]').forEach(b=>b.onclick=()=>openStaffTask(+b.dataset.openTeamTask));return}
 $('#saveFollowup').onclick=()=>{p.next=$('#nextFollowup').value;tasks.unshift({id:'task-'+Date.now().toString(36),title:`Follow up with ${p.name}`,time:currentTimeText(),createdAt:currentTimeText(),day:'Today',sub:p.next+' · Client follow-up',type:'Work',category:'Follow-up',client:p.name,done:false});store.set('tide_tasks',tasks);renderTasks();renderPeople();$('#modal').classList.remove('open');toast('Follow-up added to the To Do List.')};$('#personCall').onclick=()=>toast('Add a phone number to call directly.');$('#personWhatsapp').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent('Hi '+p.name+', just following up.'),'_blank');$('#personCopy').onclick=()=>{navigator.clipboard?.writeText('Hi '+p.name+', just following up on our last conversation.');toast('Message copied.')}
}
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPeople(b.dataset.filter,$('#peopleSearch').value)});$('#peopleSearch').oninput=e=>renderPeople($('.filters button.active').dataset.filter,e.target.value);
function renderRoutine(){$('#routineList').innerHTML=routine.map(r=>`<div class="routine-item"><time>${r[0]}</time><span class="routine-dot">${r[1]}</span><div><strong>${r[2]}</strong><small>${r[3]}</small></div></div>`).join('')}
function renderRules(){$('#ruleCount').textContent=`${rules.length} rules`;$('#rulesList').innerHTML=rules.map((r,i)=>`<div class="rule-item"><span class="rule-number">0${i+1}</span><p>${escapeHtml(r)}</p><button data-del-rule="${i}">×</button></div>`).join('');$$('[data-del-rule]').forEach(b=>b.onclick=()=>{rules.splice(+b.dataset.delRule,1);store.set('tide_rules',rules);renderRules()})}
function spokenNumber(text){let words={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,half:.5};let m=text.match(/\d+(?:\.\d+)?/);if(m)return+m[0];for(let w in words)if(new RegExp('\\b'+w+'\\b').test(text))return words[w];return 1}
function durationMinutes(text){let n=spokenNumber(text);if(/hour|hr\b/.test(text))return n*60;if(/minute|min\b/.test(text))return n;return 60}
function analyseRoutineText(raw){let text=raw.toLowerCase(),n=spokenNumber(text),now=new Date().toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),base={id:'routine-'+Date.now().toString(36),text:raw,time:now};
 const foods={burger:520,'pizza':285,'roti':110,'chapati':110,'egg':78,'banana':105,'apple':95,'rice':205,'chicken':240,'sandwich':350,'coffee':80,'tea':60,'salad':150,'dal':180,'biryani':550};let food=Object.keys(foods).find(x=>text.includes(x));
 if(food){let kcal=Math.round(foods[food]*n);return{...base,category:'Food',icon:'♨',value:kcal,unit:'kcal',detail:`Estimated ${n} × ${food} · editable`}}
 if(/water|hydration|litre|liter|\bml\b/.test(text)){let amount=n;if(/litre|liter|\bl\b/.test(text))amount*=1000;if(!/ml|litre|liter|\bl\b/.test(text))amount*=250;return{...base,category:'Water',icon:'≈',value:Math.round(amount),unit:'ml',detail:'Added to hydration'}}
 if(/workout|gym|run|running|walk|cycling|exercise|yoga|swim/.test(text)){let min=durationMinutes(text),rate=/run|running/.test(text)?600:/walk/.test(text)?250:/cycling/.test(text)?500:/yoga/.test(text)?220:/swim/.test(text)?550:450,burn=Math.round(min/60*rate);return{...base,category:'Workout',icon:'⌁',value:burn,unit:'kcal burned',detail:`${Math.round(min)} min · estimated`}}
 if(/sleep|slept|nap/.test(text)){let hours=durationMinutes(text)/60;return{...base,category:'Sleep',icon:'☾',value:+hours.toFixed(1),unit:'hours',detail:hours>=7?'Good recovery':'Below sleep target'}}
 if(/work|focus|meeting|proposal|office|client/.test(text)){let hours=durationMinutes(text)/60;return{...base,category:'Work',icon:'→',value:+hours.toFixed(1),unit:'hours',detail:'Focused work logged'}}
 return{...base,category:'Personal',icon:'♡',value:1,unit:'entry',detail:'Personal routine note'}
}
function trackRoutineEntry(text){if(!text.trim())return null;let entry=analyseRoutineText(text.trim());routineLogs.unshift(entry);store.set('tide_routine_logs',routineLogs);renderRoutineTracker();toast(`${entry.category} tracked automatically · ${entry.value} ${entry.unit}`);return entry}
function metricTotal(cat){let list=routineLogs.filter(x=>x.category===cat);if(cat==='Sleep')return list[0]?.value||0;return list.reduce((a,x)=>a+(+x.value||0),0)}
function renderRoutineTracker(){
 let data=[['Food','♨',metricTotal('Food'),'kcal','2,000','#e9824f'],['Water','≈',metricTotal('Water'),'ml','2,500','#3d9db0'],['Workout','⌁',metricTotal('Workout'),'kcal','400','#45a577'],['Sleep','☾',metricTotal('Sleep'),'hrs','8','#7468b1'],['Focus work','→',metricTotal('Work'),'hrs','6','#d79b3e']];
 $('#routineMetrics').innerHTML=data.map(d=>{let target=parseFloat(d[4].replace(',','')),pct=Math.min(1,(+d[2]||0)/target);return`<div class="routine-metric" style="--metric-color:${d[5]};--metric-progress:${pct}"><div class="routine-metric-head"><span class="routine-metric-icon">${d[1]}</span><span>${Math.round(pct*100)}%</span></div><strong>${Number(d[2]).toLocaleString('en-IN',{maximumFractionDigits:1})}</strong><small>${d[3]} · target ${d[4]}</small></div>`}).join('');
 $('#routineTimeline').innerHTML=routineLogs.length?routineLogs.map(x=>`<div class="routine-log"><span class="routine-log-icon">${x.icon}</span><div><strong>${escapeHtml(x.text)}</strong><small>${x.category} · ${x.time} · ${escapeHtml(x.detail)}</small></div><div class="routine-log-value"><b>${x.value}</b><span>${x.unit}</span><button data-delete-routine="${x.id}">×</button></div></div>`).join(''):'<div class="empty-agenda"><span>✦</span><strong>Your timeline is ready</strong><p>Speak or type your first update above.</p></div>';
 $$('[data-delete-routine]').forEach(b=>b.onclick=()=>{routineLogs=routineLogs.filter(x=>x.id!==b.dataset.deleteRoutine);store.set('tide_routine_logs',routineLogs);renderRoutineTracker()});renderRoutineSchedule();renderRoutineReport(currentRoutineReport)
}
function renderRoutineSchedule(){$('#routineSchedule').innerHTML=routineSchedule.map((x,i)=>`<div class="schedule-row"><time>${x.time}</time><span>${x.icon}</span><div><strong>${escapeHtml(x.title)}</strong><small>${x.days} · ${x.category}</small></div><button data-delete-schedule="${i}">×</button></div>`).join('');$$('[data-delete-schedule]').forEach(b=>b.onclick=()=>{routineSchedule.splice(+b.dataset.deleteSchedule,1);store.set('tide_routine_schedule',routineSchedule);renderRoutineSchedule()})}
let currentRoutineReport='daily';
function renderRoutineReport(view='daily'){currentRoutineReport=view;let daily=[68,metricTotal('Water')/2500*100,metricTotal('Workout')/400*100,metricTotal('Sleep')/8*100,metricTotal('Work')/6*100],values=view==='daily'?daily:view==='weekly'?[74,78,63,82,71]:[70,73,68,76,75],labels=['Food','Water','Move','Sleep','Work'];$('#routineReportEyebrow').textContent=view.toUpperCase()+' REPORT';$('#routineReportTitle').textContent=view==='daily'?'How your day is balancing.':view==='weekly'?'Your week, with useful patterns.':'Your month, without the noise.';$('#routineChart').innerHTML=values.map((v,i)=>`<div class="chart-bar-wrap"><div class="chart-bar" style="height:${Math.max(8,Math.min(100,v))}%"></div><span>${labels[i]}</span></div>`).join('');let water=metricTotal('Water'),sleep=metricTotal('Sleep');$('#routineInsight').innerHTML=`<span>✦</span><h3>${view==='daily'?'Today’s AI insight':view==='weekly'?'Weekly pattern':'Monthly direction'}</h3><p>${view==='daily'?(water<1500?'Hydration is the clearest opportunity today. ':'Water is looking steady. ')+(sleep<7?'Aim for an earlier wind-down tonight.':'Your sleep is supporting recovery.'):'Your strongest consistency is focused work. Keep improving sleep and regular movement without trying to perfect every day.'}</p><ul><li>Food and exercise values are estimates</li><li>Tap any entry to review later</li><li>Consistency matters more than one score</li></ul>`;$$('[data-routine-report]').forEach(b=>b.classList.toggle('active',b.dataset.routineReport===view))}
function openRoutineScheduleModal(){modal('Add to routine schedule','Build a timetable that fits your real life.',`<div class="form-field"><label>ROUTINE</label><input id="scheduleTitle" placeholder="e.g. Evening walk"></div><div class="form-field"><label>TIME</label><input id="scheduleTime" type="time"></div><div class="form-field"><label>CATEGORY</label><select id="scheduleCategory"><option>Food</option><option>Water</option><option>Workout</option><option>Sleep</option><option>Work</option><option>Personal</option></select></div><div class="form-field"><label>DAYS</label><select id="scheduleDays"><option>Every day</option><option>Mon–Fri</option><option>Mon, Wed, Fri</option><option>Weekends</option></select></div>`,()=>{let title=$('#scheduleTitle').value.trim(),raw=$('#scheduleTime').value,category=$('#scheduleCategory').value;if(!title||!raw)return toast('Add the routine and time first.');let icons={Food:'♨',Water:'≈',Workout:'⌁',Sleep:'☾',Work:'→',Personal:'♡'},time=new Date('2026-01-01T'+raw).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'});routineSchedule.push({title,time,category,icon:icons[category],days:$('#scheduleDays').value});store.set('tide_routine_schedule',routineSchedule);tasks.push({id:'task-'+Date.now().toString(36),title,time,day:'Today',sub:`Routine · ${category}`,type:category==='Work'?'Work':'Personal',category:'Reminder',done:false});store.set('tide_tasks',tasks);renderTasks();renderRoutineSchedule();$('#modal').classList.remove('open');toast('Added to your routine schedule.')})}
function meetingDateISO(m){if(m.date)return m.date;return taskDateISO({day:m.day||'Today'})}
function renderTodayCards(){let today=localISO(),cats={'Meeting':tasks.filter(t=>taskDateISO(t)===today&&taskCategory(t)==='Meeting'),'Reminder':tasks.filter(t=>taskDateISO(t)===today&&taskCategory(t)==='Reminder'),'Follow-up':tasks.filter(t=>taskDateISO(t)===today&&taskCategory(t)==='Follow-up'),'Task':tasks.filter(t=>taskDateISO(t)===today&&taskCategory(t)==='Task')},config=[['Meeting','todayMeetingTitle','todayMeetingMeta','meetingProgress','meetingProgressCount','No meetings today'],['Reminder','todayReminderTitle','todayReminderMeta','reminderProgress','reminderProgressCount','No reminders today'],['Follow-up','todayFollowupTitle','todayFollowupMeta','followupProgress','followupProgressCount','No follow-ups today'],['Task','todayTaskTitle','todayTaskMeta','taskProgress','taskProgressCount','No general tasks today']];config.forEach(([cat,titleId,metaId,barId,countId,empty])=>{let list=cats[cat],pending=list.filter(x=>!x.done),next=pending[0],done=list.filter(x=>x.done).length,pct=list.length?done/list.length*100:0;$('#'+titleId).textContent=next?.title||empty;$('#'+metaId).textContent=next?`${next.time} · ${cat}`:list.length?'All caught up':'Tap ＋ to add one';$('#'+barId).style.width=pct+'%';$('#'+countId).textContent=`${done}/${list.length}`})}
function prettyDateParts(date){let d=new Date(date+'T00:00:00');return{day:d.toLocaleDateString('en-IN',{day:'2-digit'}),rest:d.toLocaleDateString('en-IN',{month:'short',weekday:'short'})}}
function taskCategory(t){if(t.category&&['Meeting','Reminder','Follow-up','Task'].includes(t.category))return t.category;if(meetings.some(m=>m.title.toLowerCase()===t.title.toLowerCase()&&meetingDateISO(m)===taskDateISO(t)))return'Meeting';if(t.type==='BMC'||t.type==='Personal'||/remind|reminder/i.test(t.title+' '+(t.sub||'')))return'Reminder';if(t.type==='Work'&&/call|follow|client|payment|proposal|lead/i.test(t.title+' '+(t.sub||'')))return'Follow-up';return'Task'}
function renderDedicatedPages(){renderMeetingsPage();renderRemindersPage();renderFollowupsPage();renderTasksPage()}
function renderMeetingsPage(){let list=[...meetings].sort((a,b)=>meetingDateISO(a).localeCompare(meetingDateISO(b))||(a.time||'').localeCompare(b.time||''));$('#meetingsPageList').innerHTML=list.length?list.map((m,i)=>{let d=prettyDateParts(meetingDateISO(m)),linked=tasks.find(t=>t.title.toLowerCase()===m.title.toLowerCase()&&taskDateISO(t)===meetingDateISO(m));return`<div class="dedicated-card"><div class="dedicated-date"><strong>${d.day}</strong><span>${d.rest}</span></div><div><h3 style="${linked?.done?'text-decoration:line-through;opacity:.55':''}">${escapeHtml(m.title)}</h3><p>${escapeHtml(m.client||m.sub||'Meeting')}</p><div class="dedicated-card-meta"><span>Meeting</span><span>${linked?.done?'Completed':escapeHtml(m.kind||'Scheduled')}</span></div></div><div class="dedicated-time"><strong>${m.time||currentTimeText()}</strong><span>${meetingDateISO(m)}</span><div class="dedicated-actions"><button data-meeting-calendar>Calendar</button><button data-meeting-action>Next action</button>${linked?`<button data-meeting-check="${linked.id}">${linked.done?'Undo':'Complete'}</button>`:''}</div></div></div>`}).join(''):'<div class="empty-agenda"><span>□</span><strong>No meetings scheduled</strong><p>Add a meeting when something comes up.</p></div>';$$('[data-meeting-calendar]').forEach(b=>b.onclick=()=>switchTab('calendar'));$$('[data-meeting-action]').forEach(b=>b.onclick=finishMeeting);$$('[data-meeting-check]').forEach(b=>b.onclick=()=>toggleTaskEverywhere(b.dataset.meetingCheck))}
function reminderTasks(){return tasks.filter(t=>taskCategory(t)==='Reminder')}
function renderRemindersPage(){let list=reminderTasks().sort((a,b)=>taskDateISO(a).localeCompare(taskDateISO(b))),today=localISO(),active=list.filter(x=>!x.done),todayCount=active.filter(x=>taskDateISO(x)===today).length,upcoming=active.filter(x=>taskDateISO(x)>today).length,done=list.filter(x=>x.done).length;$('#reminderSummary').innerHTML=`<div class="dedicated-stat"><strong>${todayCount}</strong><span>Today</span></div><div class="dedicated-stat"><strong>${upcoming}</strong><span>Upcoming</span></div><div class="dedicated-stat"><strong>${done}</strong><span>Completed</span></div>`;$('#remindersPageList').innerHTML=list.length?list.map(t=>{let d=prettyDateParts(taskDateISO(t));return`<div class="dedicated-card"><div class="dedicated-date"><strong>${d.day}</strong><span>${d.rest}</span></div><div><h3 style="${t.done?'text-decoration:line-through;opacity:.55':''}">${escapeHtml(t.title)}</h3><p>${escapeHtml(t.sub||t.type)}</p><div class="dedicated-card-meta"><span>${t.type}</span><span>${t.done?'Completed':'Pending'}</span></div></div><div class="dedicated-time"><strong>${t.time}</strong><span>${taskDateISO(t)}</span><div class="dedicated-actions"><button data-reminder-open="${t.id}">Open task</button></div></div></div>`}).join(''):'<div class="empty-agenda"><span>◉</span><strong>No reminders yet</strong><p>Add one and it will also enter your To Do List.</p></div>';$$('[data-reminder-open]').forEach(b=>{let t=tasks.find(x=>x.id===b.dataset.reminderOpen);b.onclick=()=>openTaskQueue(t?taskDateISO(t):localISO())})}
function followupTasks(){return tasks.filter(t=>taskCategory(t)==='Follow-up')}
function renderFollowupsPage(){let list=followupTasks().sort((a,b)=>taskDateISO(a).localeCompare(taskDateISO(b)));$('#followupsPageList').innerHTML=list.length?list.map(t=>{let d=prettyDateParts(taskDateISO(t));return`<div class="dedicated-card"><div class="dedicated-date"><strong>${d.day}</strong><span>${d.rest}</span></div><div><h3>${escapeHtml(t.title)}</h3><p>${escapeHtml(t.client||t.sub||'Client follow-up')}</p><div class="dedicated-card-meta"><span>${t.done?'Completed':'Follow-up pending'}</span><span>${escapeHtml(t.client||'Client')}</span></div></div><div class="dedicated-time"><strong>${t.time}</strong><span>${taskDateISO(t)}</span><div class="dedicated-actions"><button data-follow-edit="${t.id}">Edit</button><button data-follow-whatsapp="${t.id}">WhatsApp</button></div></div></div>`}).join(''):'<div class="empty-agenda"><span>↗</span><strong>No follow-ups waiting</strong><p>Add a client follow-up when needed.</p></div>';$$('[data-follow-edit]').forEach(b=>b.onclick=()=>openEditTask(b.dataset.followEdit));$$('[data-follow-whatsapp]').forEach(b=>b.onclick=()=>{let t=tasks.find(x=>x.id===b.dataset.followWhatsapp);window.open('https://wa.me/?text='+encodeURIComponent('Hi, following up regarding '+(t?.title||'our discussion')),'_blank')})}
function renderTasksPage(){let list=tasks.filter(t=>taskCategory(t)==='Task').sort((a,b)=>taskDateISO(a).localeCompare(taskDateISO(b)));$('#tasksPageList').innerHTML=list.length?list.map(t=>{let d=prettyDateParts(taskDateISO(t));return`<div class="dedicated-card"><div class="dedicated-date"><strong>${d.day}</strong><span>${d.rest}</span></div><div><h3 style="${t.done?'text-decoration:line-through;opacity:.55':''}">${escapeHtml(t.title)}</h3><p>${escapeHtml(t.sub||t.type)}</p><div class="dedicated-card-meta"><span>Task</span><span>${t.done?'Completed':'Pending'}</span></div></div><div class="dedicated-time"><strong>${t.time}</strong><span>${taskDateISO(t)}</span><div class="dedicated-actions"><button data-general-open="${t.id}">Open task</button></div></div></div>`}).join(''):'<div class="empty-agenda"><span>☷</span><strong>No general tasks</strong><p>Anything not classified as a meeting, reminder or follow-up appears here.</p></div>';$$('[data-general-open]').forEach(b=>{let t=tasks.find(x=>x.id===b.dataset.generalOpen);b.onclick=()=>openTaskQueue(t?taskDateISO(t):localISO())})}
function renderCategoryGlassList(category,list,containerId){let ordered=[...list].sort((a,b)=>taskDateISO(a).localeCompare(taskDateISO(b))||a.time.localeCompare(b.time)),groups={};ordered.forEach(t=>(groups[taskDateISO(t)]??=[]).push(t));$('#'+containerId).innerHTML=Object.keys(groups).length?Object.entries(groups).map(([date,items])=>{let d=new Date(date+'T00:00:00');return`<div class="category-page-day"><div class="month-day-head"><strong>${d.toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</strong><span>${d.toLocaleDateString('en-IN',{weekday:'long'})}</span></div><div class="category-page-list">${items.map(t=>`<div class="category-page-row" data-category-task="${t.id}"><span class="category-page-accent ${category.toLowerCase().replace('-','')}"></span><div><strong style="${t.done?'text-decoration:line-through;opacity:.5':''}">${escapeHtml(t.title)}</strong><p>${escapeHtml(t.client||t.sub||category)}</p></div><time>${t.time}</time><button class="month-check ${t.done?'checked':''}" data-category-check="${t.id}">${t.done?'✓':''}</button></div>`).join('')}</div></div>`}).join(''):`<div class="empty-agenda"><span>□</span><strong>No ${category.toLowerCase()} items</strong><p>Use the add button above when something comes up.</p></div>`;$$('[data-category-task]').forEach(r=>r.onclick=()=>{let i=tasks.findIndex(t=>t.id===r.dataset.categoryTask);if(i>=0)openTaskActions(i)});$$('[data-category-check]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTaskEverywhere(b.dataset.categoryCheck)})}
renderMeetingsPage=()=>renderCategoryGlassList('Meeting',tasks.filter(t=>taskCategory(t)==='Meeting'),'meetingsPageList');
renderRemindersPage=()=>{let list=reminderTasks(),today=localISO(),active=list.filter(x=>!x.done);$('#reminderSummary').innerHTML=`<div class="dedicated-stat"><strong>${active.filter(x=>taskDateISO(x)===today).length}</strong><span>Today</span></div><div class="dedicated-stat"><strong>${active.filter(x=>taskDateISO(x)>today).length}</strong><span>Upcoming</span></div><div class="dedicated-stat"><strong>${list.filter(x=>x.done).length}</strong><span>Completed</span></div>`;renderCategoryGlassList('Reminder',list,'remindersPageList')};
renderFollowupsPage=()=>renderCategoryGlassList('Follow-up',followupTasks(),'followupsPageList');
renderTasksPage=()=>renderCategoryGlassList('Task',tasks.filter(t=>taskCategory(t)==='Task'),'tasksPageList');
function openAddReminder(){let now=new Date();modal('Add reminder','It will appear here and in your To Do List.',`<div class="form-field"><label>REMINDER</label><input id="newReminderTitle" placeholder="What should I remind you about?"></div><div class="quick-fields-row"><div class="form-field"><label>DATE</label><input id="newReminderDate" type="date" value="${localISO()}"></div><div class="form-field"><label>TIME</label><input id="newReminderTime" type="time" value="${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}"></div><div class="form-field"><label>TYPE</label><select id="newReminderType"><option>Personal</option><option>BMC</option></select></div></div>`,()=>{let title=$('#newReminderTitle').value.trim(),date=$('#newReminderDate').value,raw=$('#newReminderTime').value;if(!title)return toast('Write the reminder first.');tasks.unshift({id:'task-'+Date.now().toString(36),title,date,day:dateLabel(date),time:new Date('2026-01-01T'+raw).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),type:$('#newReminderType').value,category:'Reminder',sub:'Reminder',done:false});store.set('tide_tasks',tasks);renderTasks();$('#modal').classList.remove('open');toast('Reminder added to the To Do List.')})}
function openAddFollowup(){let now=new Date();modal('Add client follow-up','It will appear here and in your To Do List.',`<div class="form-field"><label>CLIENT / FOLLOW-UP</label><input id="newFollowupTitle" placeholder="e.g. Call Rohan about proposal"></div><div class="quick-fields-row"><div class="form-field"><label>DATE</label><input id="newFollowupDate" type="date" value="${localISO()}"></div><div class="form-field"><label>TIME</label><input id="newFollowupTime" type="time" value="${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}"></div><div class="form-field"><label>TYPE</label><select><option>Client</option></select></div></div>`,()=>{let title=$('#newFollowupTitle').value.trim(),date=$('#newFollowupDate').value,raw=$('#newFollowupTime').value;if(!title)return toast('Write the follow-up first.');tasks.unshift({id:'task-'+Date.now().toString(36),title,date,day:dateLabel(date),time:new Date('2026-01-01T'+raw).toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}),type:'Work',category:'Follow-up',sub:'Client follow-up',done:false});store.set('tide_tasks',tasks);renderTasks();$('#modal').classList.remove('open');toast('Follow-up added to the To Do List.')})}
let monthFeedOffset=0,activeMonthDate=localISO(),currentMonthGroups={};
function monthFeedItems(){let combined=[...tasks.map(t=>{let cat=taskCategory(t),kind=cat==='Follow-up'?'followup':cat.toLowerCase();return{title:t.title,time:t.time||currentTimeText(),date:taskDateISO(t),taskId:t.id,pendingSince:t.pendingSince||'',kind,category:cat,meta:[t.client,t.service,cat,t.done?'Completed':'Pending'].filter(Boolean).join(' · '),done:t.done}}),...meetings.map(m=>({title:m.title,time:m.time||currentTimeText(),date:meetingDateISO(m),kind:'meeting',category:'Meeting',meta:m.client||m.sub||'Meeting',done:false}))];let seen=new Set();return combined.filter(x=>{let key=x.date+'|'+x.title.toLowerCase();if(seen.has(key))return false;seen.add(key);return true})}
function renderMonthFeed(offset=monthFeedOffset){monthFeedOffset=offset;let base=new Date(),view=new Date(base.getFullYear(),base.getMonth()+offset,1),year=view.getFullYear(),month=view.getMonth(),items=monthFeedItems().filter(x=>{let d=new Date(x.date+'T00:00:00');return d.getFullYear()===year&&d.getMonth()===month}).sort((a,b)=>a.time.localeCompare(b.time)),groups={};items.forEach(x=>(groups[x.date]??=[]).push(x));currentMonthGroups=groups;let daysInMonth=new Date(year,month+1,0).getDate(),allMonthDates=Array.from({length:daysInMonth},(_,i)=>localISO(new Date(year,month,i+1))),sameMonth=year===base.getFullYear()&&month===base.getMonth();if(!allMonthDates.includes(activeMonthDate))activeMonthDate=sameMonth?localISO():allMonthDates[0];$('#monthFeedTitle').textContent=view.toLocaleDateString('en-IN',{month:'long',year:'numeric'});$('#monthDateRail').innerHTML=allMonthDates.map(date=>{let d=new Date(date+'T00:00:00');return`<button class="date-rail-pill ${date===activeMonthDate?'active':''}" data-rail-date="${date}"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('en-IN',{weekday:'short'})}</span></button>`}).join('');renderSelectedMonthDate(activeMonthDate);$$('[data-rail-date]').forEach(b=>b.onclick=()=>selectMonthDate(b.dataset.railDate));requestAnimationFrame(()=>document.querySelector('.date-rail-pill.active')?.scrollIntoView({behavior:'auto',inline:'center',block:'nearest'}))}
function selectedMonthDateHtml(date){let d=new Date(date+'T00:00:00'),list=currentMonthGroups[date]||[],categoryOrder=['Meeting','Reminder','Follow-up','Task'];return`<div class="month-day active-date" data-month-date="${date}"><div class="month-day-head"><strong>${d.toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</strong><span>${d.toLocaleDateString('en-IN',{weekday:'long'})}</span></div>${list.length?`<div class="month-category-groups">${categoryOrder.map(category=>{let categoryItems=list.filter(x=>(x.category||'Task')===category);if(!categoryItems.length)return'';let kind=category==='Follow-up'?'followup':category.toLowerCase();return`<div class="month-category-block"><span class="month-category-strip ${kind}">${category}</span><div class="month-category-items">${categoryItems.map(x=>`<div class="month-group-row" data-feed-date="${date}" data-feed-task="${x.taskId||''}" data-feed-category="${category}"><div>${x.pendingSince?`<span class="pending-from">Pending from ${new Date(x.pendingSince+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span>`:''}<strong style="${x.done?'text-decoration:line-through;opacity:.5':''}">${escapeHtml(x.title)}</strong></div>${x.taskId?`<button class="month-check ${x.done?'checked':''}" data-month-check="${x.taskId}">${x.done?'✓':''}</button>`:'<span></span>'}</div>`).join('')}</div></div>`}).join('')}</div>`:`<div class="summary-box">No tasks for this date. <button class="empty-date-add" id="emptyDateAdd">＋ Add task</button></div>`}</div>`}
function renderSelectedMonthDate(date){$('#monthTaskFeed').innerHTML=selectedMonthDateHtml(date);$('#emptyDateAdd')?.addEventListener('click',()=>openQuickAddTask(date));$$('[data-feed-date]').forEach(x=>x.onclick=()=>{if(x.dataset.feedCategory==='Meeting'&&x.dataset.feedTask){let i=tasks.findIndex(t=>t.id===x.dataset.feedTask);if(i>=0)return openTaskActions(i)}openTaskQueue(x.dataset.feedDate)});$$('[data-month-check]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTaskEverywhere(b.dataset.monthCheck)});}
function selectMonthDate(date){activeMonthDate=date;$$('[data-rail-date]').forEach(x=>{let active=x.dataset.railDate===date;x.classList.toggle('active',active);if(active)x.scrollIntoView({behavior:'smooth',inline:'center',block:'nearest'})});renderSelectedMonthDate(date)}

function moveReopenedTaskToToday(task){let due=taskDateISO(task),today=localISO();if(due<today){task.pendingSince=task.pendingSince||due;task.originalDate=task.originalDate||due;task.date=today;task.day='Today';task.sub=`Pending from ${task.pendingSince} · ${taskCategory(task)}`}}
function toggleTaskEverywhere(id){let task=tasks.find(t=>t.id===id);if(!task)return;let y=window.scrollY;task.done=!task.done;if(task.done)task.completedAt=currentTimeText();else{delete task.completedAt;moveReopenedTaskToToday(task)}store.set('tide_tasks',tasks);renderTasks();renderCalendar(weekOffset);if(currentCalendarView!=='daily')renderCalendarOverview(currentCalendarView);requestAnimationFrame(()=>window.scrollTo({top:y,behavior:'auto'}));toast(task.done?'Completed everywhere.':task.pendingSince?'Moved to Today as an overdue task.':'Moved back to pending everywhere.')}
let selectedCalIndex=(new Date().getDay()+6)%7;
function itemDay(x){if(x.day)return x.day;if((x.sub||'').includes('Tomorrow'))return'Tomorrow';return'Today'}
function allCalendarItems(){return tasks.map((x,i)=>({...x,source:taskCategory(x),sourceIndex:i}))}
function detailMeta(x){return [x.client&&`Client: ${x.client}`,x.service&&`Service: ${x.service}`,x.assignee&&x.assignee!=='Myself'&&`Assigned: ${x.assignee}`,x.notes].filter(Boolean)}
function renderCalendar(offset=0){
 let names=['MON','TUE','WED','THU','FRI','SAT','SUN'],today=new Date(),monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7)+offset*7);let dates=names.map((_,i)=>{let d=new Date(monday);d.setDate(monday.getDate()+i);return d});
 $('#weekDays').innerHTML=dates.map((d,i)=>`<div class="day ${i===selectedCalIndex?'active':''}" data-cal-day="${i}" role="button" tabindex="0"><small>${names[i]}</small><strong>${d.getDate()}</strong></div>`).join('');
 $('#calRange').textContent=`${dates[0].toLocaleDateString('en-IN',{day:'numeric',month:'short'})}–${dates[6].toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}`;
 $$('[data-cal-day]').forEach(d=>{d.onclick=()=>{selectedCalIndex=+d.dataset.calDay;renderCalendar(offset)};d.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();d.click()}}});
 let selectedDate=localISO(dates[selectedCalIndex]),tom=new Date();tom.setDate(tom.getDate()+1),label=selectedDate===localISO()?'Today':selectedDate===localISO(tom)?'Tomorrow':dates[selectedCalIndex].toLocaleDateString('en-IN',{weekday:'long'}),all=allCalendarItems(),list=all.filter(x=>taskDateISO(x)===selectedDate);
 $('#agenda').innerHTML=`<div class="agenda-label"><strong>${label} — Detailed tasks</strong><span>${list.length} ${list.length===1?'item':'items'}</span></div>`+(list.length?list.map(x=>`<div class="agenda-row"><time>${x.time||currentTimeText()}</time><div class="event calendar-event ${x.source.toLowerCase().replace('-','')}" data-calendar-index="${x.sourceIndex}"><div><h4 style="${x.done?'text-decoration:line-through;opacity:.5':''}">${escapeHtml(x.title)}</h4><p>${x.source}</p><div class="event-details">${detailMeta(x).map(m=>`<span>${escapeHtml(m)}</span>`).join('')||`<span>${escapeHtml(x.sub||'No extra details')}</span>`}</div></div><button class="calendar-check ${x.done?'checked':''}" data-calendar-check="${x.id}">${x.done?'✓':''}</button></div></div>`).join(''):`<div class="empty-agenda"><span>□</span><strong>Nothing planned for ${label.toLowerCase()}</strong><p>Your time is open. Add a task whenever needed.</p></div>`);
 $$('[data-calendar-index]').forEach(e=>e.onclick=()=>openTaskActions(+e.dataset.calendarIndex));$$('[data-calendar-check]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTaskEverywhere(b.dataset.calendarCheck)});
 $('#upcomingList').innerHTML=all.filter(x=>!x.done&&taskDateISO(x)>=localISO()).sort((a,b)=>taskDateISO(a).localeCompare(taskDateISO(b))).slice(0,5).map(x=>`<div class="upcoming-item"><strong>${escapeHtml(x.title)}</strong><span>${taskDateISO(x)} · ${x.time} · ${x.source}</span></div>`).join('')
}
function renderCalendarOverview(view){
 let today=new Date();
 if(view==='monthly'){
  let year=today.getFullYear(),month=today.getMonth(),first=new Date(year,month,1),last=new Date(year,month+1,0),startPad=(first.getDay()+6)%7,cells=[];for(let i=0;i<startPad;i++)cells.push(null);for(let d=1;d<=last.getDate();d++)cells.push(new Date(year,month,d));
  $('#calendarOverview').innerHTML=`<div class="google-month-head"><div><p class="eyebrow">MONTH CALENDAR</p><h2>${first.toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</h2></div><span>${tasks.filter(t=>taskDateISO(t).startsWith(`${year}-${String(month+1).padStart(2,'0')}`)).length} scheduled</span></div><div class="google-month-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="google-weekday">${x}</div>`).join('')}${cells.map(d=>{if(!d)return'<div class="google-day empty"></div>';let iso=localISO(d),dayTasks=tasks.filter(t=>taskDateISO(t)===iso);return`<div class="google-day ${iso===localISO()?'today':''}" data-month-calendar-date="${iso}"><strong>${d.getDate()}</strong><div>${dayTasks.slice(0,3).map(t=>`<span class="google-task ${taskCategory(t).toLowerCase().replace('-','')} ${t.done?'done':''}">${escapeHtml(t.title)}<button data-calendar-mini-check="${t.id}">${t.done?'✓':'○'}</button></span>`).join('')}${dayTasks.length>3?`<small>+${dayTasks.length-3} more</small>`:''}</div></div>`}).join('')}</div><div class="calendar-month-agenda" id="calendarMonthAgenda"></div>`;setTimeout(()=>renderCalendarMonthAgenda(localISO()),0);
 }else{
  let monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7));let dates=[0,1,2,3,4,5,6].map(i=>{let d=new Date(monday);d.setDate(monday.getDate()+i);return d});$('#calendarOverview').innerHTML=`<div class="google-month-head"><div><p class="eyebrow">WEEKLY SCHEDULE</p><h2>${dates[0].toLocaleDateString('en-IN',{day:'numeric',month:'short'})}–${dates[6].toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</h2></div></div><div class="weekly-board">${dates.map(d=>{let iso=localISO(d),list=tasks.filter(t=>taskDateISO(t)===iso);return`<div class="weekly-column"><div class="weekly-column-head ${iso===localISO()?'active':''}"><strong>${d.toLocaleDateString('en-IN',{weekday:'short'})}</strong><span>${d.getDate()}</span></div>${list.map(t=>`<div class="weekly-task ${taskCategory(t).toLowerCase().replace('-','')}"><span style="${t.done?'text-decoration:line-through;opacity:.5':''}">${escapeHtml(t.title)}</span><button data-calendar-mini-check="${t.id}">${t.done?'✓':'○'}</button></div>`).join('')||'<small class="weekly-empty">Open</small>'}</div>`}).join('')}</div>`
 }
 $$('[data-calendar-mini-check]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTaskEverywhere(b.dataset.calendarMiniCheck)});$$('[data-month-calendar-date]').forEach(x=>x.onclick=e=>{if(!e.target.closest('button'))renderCalendarMonthAgenda(x.dataset.monthCalendarDate)})
}
function renderCalendarMonthAgenda(date){let box=$('#calendarMonthAgenda');if(!box)return;$$('[data-month-calendar-date]').forEach(x=>x.classList.toggle('selected',x.dataset.monthCalendarDate===date));let d=new Date(date+'T00:00:00'),list=tasks.filter(t=>taskDateISO(t)===date);box.innerHTML=`<div class="calendar-month-agenda-head"><strong>${d.toLocaleDateString('en-IN',{day:'numeric',month:'long',weekday:'long'})}</strong><span>${list.length} items</span></div>${list.length?list.map(t=>`<div class="calendar-agenda-item ${taskCategory(t).toLowerCase().replace('-','')}" data-calendar-agenda-task="${t.id}"><div><strong style="${t.done?'text-decoration:line-through;opacity:.5':''}">${escapeHtml(t.title)}</strong><small>${t.time} · ${taskCategory(t)}</small></div><button class="calendar-check ${t.done?'checked':''}" data-calendar-agenda-check="${t.id}">${t.done?'✓':''}</button></div>`).join(''):'<div class="summary-box">Nothing scheduled for this date.</div>'}`;$$('[data-calendar-agenda-task]').forEach(r=>r.onclick=()=>{let i=tasks.findIndex(t=>t.id===r.dataset.calendarAgendaTask);if(i>=0)openTaskActions(i)});$$('[data-calendar-agenda-check]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleTaskEverywhere(b.dataset.calendarAgendaCheck)})}
let weekOffset=0;$('#prevWeek').onclick=()=>{selectedCalIndex=0;renderCalendar(--weekOffset)};$('#nextWeek').onclick=()=>{selectedCalIndex=0;renderCalendar(++weekOffset)};$('#todayBtn').onclick=()=>{weekOffset=0;selectedCalIndex=(new Date().getDay()+6)%7;renderCalendar()};
let currentCalendarView='daily';$$('[data-calendar-view]').forEach(b=>b.onclick=()=>{currentCalendarView=b.dataset.calendarView;$$('[data-calendar-view]').forEach(x=>x.classList.toggle('active',x===b));let daily=b.dataset.calendarView==='daily';$('#dailyCalendarView').classList.toggle('hidden',!daily);$('#calendarOverview').classList.toggle('active',!daily);if(!daily)renderCalendarOverview(b.dataset.calendarView)});
function modal(title,desc,fields,action){$('#modalBody').innerHTML=`<h2>${title}</h2><p>${desc}</p>${fields}<div class="form-actions"><button class="primary" id="modalSave">Save</button></div>`;$('#modal').classList.add('open');$('#modalSave').onclick=action}
function closeMainModal(e){e?.preventDefault?.();e?.stopPropagation?.();$('#modal').classList.remove('open','focus-chooser')}bindFastTap($('#modalClose'),closeMainModal);$('#modal').onclick=e=>{if(e.target.id==='modal')closeMainModal(e)};new MutationObserver(()=>{let open=$('#modal').classList.contains('open');document.body.classList.toggle('modal-open',open||$('#focusOverlay').classList.contains('open'));if(!open)$('#modal').classList.remove('focus-chooser')}).observe($('#modal'),{attributes:true,attributeFilter:['class']});
$('#addRuleBtn').onclick=()=>modal('Add a life rule','Keep it short, clear and personal.',`<div class="form-field"><label>MY RULE</label><input id="ruleInput" placeholder="e.g. Phone away at 11:30 PM" autofocus></div>`,()=>{let v=$('#ruleInput').value.trim();if(v){rules.push(v);store.set('tide_rules',rules);renderRules();$('#modal').classList.remove('open');toast('Rule added to your life system.')}});
$('#addPersonBtn').onclick=()=>modal('Add a person','Just the basics. You can add details later.',`<div class="form-field"><label>NAME</label><input id="personName" placeholder="Full name"></div><div class="form-field"><label>TYPE</label><select id="personType"><option>Lead</option><option>Client</option><option>Team</option></select></div>`,()=>{let n=$('#personName').value.trim();if(n){people.unshift({name:n,type:$('#personType').value,note:'New contact',next:'No action set'});renderPeople();$('#modal').classList.remove('open');toast('Person added.')}});
$('#addMeetingBtn').onclick=()=>modal('Schedule a meeting','Add only what you need to remember.',`<div class="form-field"><label>MEETING</label><input id="meetingTitle" placeholder="Who or what is it about?"></div><div class="form-field"><label>DATE & TIME</label><input id="meetingDate" type="datetime-local"></div>`,()=>{let title=$('#meetingTitle').value.trim(),raw=$('#meetingDate').value;if(!title)return toast('Add a meeting name first.');let d=raw?new Date(raw):new Date(),today=new Date(),tomorrow=new Date();tomorrow.setDate(today.getDate()+1);let day=d.toDateString()===tomorrow.toDateString()?'Tomorrow':d.toDateString()===today.toDateString()?'Today':d.toLocaleDateString('en-IN',{weekday:'long'}),time=raw?d.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit'}):currentTimeText();meetings.unshift({time,title,day,sub:`${day} · Added manually`,kind:''});store.set('tide_meetings',meetings);tasks.unshift({id:'task-'+Date.now().toString(36),time,title,day,sub:`${day} · Meeting`,type:'Work',category:'Meeting',done:false});store.set('tide_tasks',tasks);renderTasks();selectedCalIndex=day==='Tomorrow'?3:2;renderCalendar(0);$('#modal').classList.remove('open');toast(`Meeting added to ${day}.`)} );
function openDailyReset(){let unfinished=tasks.filter(t=>!t.done).length;$('#modalBody').innerHTML=`<h2>Two-minute daily reset</h2><p>Close today gently. Tomorrow does not need to live in your head tonight.</p><div class="summary-box"><strong>${tasks.filter(t=>t.done).length} completed today</strong><br>${unfinished} unfinished items can move to tomorrow.</div><div class="form-field"><label>TOMORROW’S FIRST TASK</label><input id="tomorrowFirst" placeholder="The one thing I’ll start with"></div><div class="form-field"><label>WAKE-UP TARGET</label><input id="wakeTarget" type="time" value="07:30"></div><div class="action-list"><button id="finishReset">✓ Move unfinished items and finish my day</button></div>`;$('#modal').classList.add('open');$('#finishReset').onclick=()=>{tasks.filter(t=>!t.done).forEach(t=>{t.day='Tomorrow';if(!t.sub.includes('Tomorrow'))t.sub='Tomorrow · '+t.type});let first=$('#tomorrowFirst').value.trim();if(first)tasks.unshift({title:first,time:currentTimeText(),createdAt:currentTimeText(),type:'Personal',category:'Task',day:'Tomorrow',sub:'Tomorrow · First task',done:false});store.set('tide_tasks',tasks);renderTasks();$('#modal').classList.remove('open');toast('Day closed. Your mind can rest now.')}}
function openBmcChecklist(task){let items=['File and application copy','ID / Aadhaar copy','Required supporting documents','Client and property details','Payment information','Name of person to meet'];$('#modalBody').innerHTML=`<h2>BMC visit checklist</h2><p>${task?escapeHtml(task.title):'Reusable before every BMC visit'}</p><div class="checklist">${items.map((x,i)=>`<label><input type="checkbox" data-bmc-check> ${x}</label>`).join('')}</div><div class="form-actions"><button class="primary" id="bmcReady">I’m ready</button></div>`;$('#modal').classList.add('open');$('#bmcReady').onclick=()=>{let n=$$('[data-bmc-check]:checked').length;if(n<items.length)return toast(`${items.length-n} checklist item${items.length-n>1?'s':''} still missing.`);$('#modal').classList.remove('open');toast('BMC checklist complete. You’re ready to go.')}}
function openReminderSettings(){let prefs=store.get('tide_reminder_prefs',[true,true,true,false]);let labels=['Gym at 6:30 PM','Phone away at 11:30 PM','Lead follow-up block at 11:00 AM','Silence work after 8:30 PM'];$('#modalBody').innerHTML=`<h2>Connected reminders</h2><p>Your rules can quietly guide your day.</p>${labels.map((x,i)=>`<div class="reminder-row"><span>${x}</span><button class="toggle ${prefs[i]?'on':''}" data-reminder="${i}"><i></i></button></div>`).join('')}<div class="form-actions"><button class="primary" id="allowNotifications">Allow notifications</button></div>`;$('#modal').classList.add('open');$$('[data-reminder]').forEach(b=>b.onclick=()=>{b.classList.toggle('on');prefs[+b.dataset.reminder]=b.classList.contains('on');store.set('tide_reminder_prefs',prefs)});$('#allowNotifications').onclick=async()=>{if('Notification'in window){let r=await Notification.requestPermission();toast(r==='granted'?'Reminders are enabled.':'Notifications were not allowed.')}else toast('Browser notifications are not supported here.')}}
function finishMeeting(){modal('What happens next?','Never leave a meeting without a next action.',`<div class="form-field"><label>NEXT ACTION</label><select id="meetingNext"><option>Send proposal</option><option>Call after three days</option><option>Collect payment</option><option>Assign work to staff</option><option>No further action</option></select></div><div class="form-field"><label>SHORT NOTE</label><input id="meetingNote" placeholder="Anything worth remembering?"></div>`,()=>{let action=$('#meetingNext').value;if(action!=='No further action'){tasks.unshift({time:currentTimeText(),createdAt:currentTimeText(),title:action,sub:'Meeting follow-up · Today',type:action.includes('staff')?'Team':'Work',category:action.includes('staff')?'Task':'Follow-up',done:false,status:action.includes('staff')?'Assigned':''});store.set('tide_tasks',tasks);renderTasks()}$('#modal').classList.remove('open');toast(action==='No further action'?'Meeting closed.':'Next action added to Today.')})}
function openSearch(){
 $('#modalBody').innerHTML=`<h2>Search everything</h2><p>Tasks, people, meetings, thoughts and BMC files.</p><div class="form-field"><input id="globalSearchInput" placeholder="Type a name, task or file reference" autofocus></div><div class="action-list" id="searchResults"><button>Start typing to search…</button></div>`;$('#modal').classList.add('open');let input=$('#globalSearchInput');setTimeout(()=>input.focus(),50);input.oninput=()=>{let q=input.value.toLowerCase().trim(),all=[...tasks.map(x=>({title:x.title,meta:'Task · '+x.type,tab:'today'})),...people.map(x=>({title:x.name,meta:x.type+' · '+x.next,tab:'people'})),...meetings.map(x=>({title:x.title,meta:'Meeting · '+x.time,tab:'calendar'})),...thoughts.map(x=>({title:x.text,meta:x.meta,tab:'dump'}))].filter(x=>q&&x.title.toLowerCase().includes(q)).slice(0,8);$('#searchResults').innerHTML=all.length?all.map((x,i)=>`<button data-result="${i}"><strong>${escapeHtml(x.title)}</strong><br><small>${x.meta}</small></button>`).join(''):'<button>No matching item found</button>';$$('[data-result]').forEach(b=>b.onclick=()=>{$('#modal').classList.remove('open');switchTab(all[+b.dataset.result].tab)})}}
$('#editRoutine').onclick=()=>switchTab('routine');
$('#dailyResetBtn').onclick=openDailyReset;$('#mobileResetBtn').onclick=openDailyReset;
$('#bmcTemplateBtn').onclick=()=>openBmcChecklist();
const ruleDays=['Protect the morning. Don’t open WhatsApp before your first task is done.','Never leave a meeting without deciding the next action.','Your health is a business asset. Move for at least thirty minutes.','Do less, but finish what you start.'];let ri=0;$('#newRuleOfDay').onclick=()=>{$('.rules-banner h2').textContent=ruleDays[++ri%ruleDays.length]};
let focusStartedAt=0,focusElapsedMs=0,focusTimerInterval=null,focusStopwatchPaused=false,focusCountdownActive=false,focusCountdownEnd=0,focusCountdownTotalMs=25*60000,focusSelectedMinutes=25;
function clockText(ms){let sec=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(sec/60),s=sec%60;return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function focusTimeText(){return clockText(focusStopwatchPaused?focusElapsedMs:Date.now()-focusStartedAt)}
function updateFocusTimer(){let value=focusTimeText();$('#focusSmallTimer').textContent=value;$('#focusBigTimer').textContent=value;if(focusCountdownActive){let left=Math.max(0,focusCountdownEnd-Date.now()),progress=Math.max(0,Math.min(1,1-left/focusCountdownTotalMs));$('#focusCountdownDisplay').textContent=clockText(left);$('#focusOrbTimer').textContent=clockText(left);$('#focusCountdownOrb').style.background=`conic-gradient(white ${progress*360}deg,rgba(255,255,255,.16) ${progress*360}deg)`;if(left<=0)finishFocusCountdown()}}
function refreshFocusTask(resetTimer=true){let i=currentTaskIndex(),task=tasks[i];if(!task)return closeFocusMode();$('#focusTaskTitle').textContent=task.title;$('#focusCategory').textContent=taskCategory(task).toUpperCase();$('#focusTaskMeta').textContent=task.pendingSince?pendingStatus(task):`${task.time} · One task. Nothing else.`;let card=$('#nextCard'),overlay=$('#focusOverlay');overlay.classList.remove('level-yellow','level-orange','level-red');if(card.classList.contains('level-yellow'))overlay.classList.add('level-yellow');if(card.classList.contains('level-orange'))overlay.classList.add('level-orange');if(card.classList.contains('level-red'))overlay.classList.add('level-red');if(resetTimer){focusStartedAt=Date.now();focusElapsedMs=0;focusStopwatchPaused=false;stopFocusCountdown(false);$('#focusCountdownOrb').classList.remove('show');$('#focusCountdownDisplay').textContent=clockText(focusSelectedMinutes*60000);$('#focusCountdownMessage').textContent='The stopwatch pauses while your countdown runs.';$('#focusCountdownStart').textContent='Start countdown';updateFocusTimer()}}
function openFocusMode(){if(currentTaskIndex()<0)return toast('Add a task before starting Focus Mode.');refreshFocusTask(true);$('#focusOverlay').classList.add('open');document.body.classList.add('modal-open');clearInterval(focusTimerInterval);focusTimerInterval=setInterval(updateFocusTimer,500)}
function closeFocusMode(){clearInterval(focusTimerInterval);focusTimerInterval=null;stopFocusCountdown(false);$('#focusOverlay').classList.remove('open','completing');$('#focusGreen').style.width='0';$('#focusBigTimer').classList.remove('show');$('#focusCountdownPanel').classList.remove('show');$('#focusCountdownOrb').classList.remove('show');document.body.classList.remove('modal-open')}
function startFocusCountdown(minutes=focusSelectedMinutes){focusSelectedMinutes=Math.max(1,+minutes||25);focusElapsedMs=Date.now()-focusStartedAt;focusStopwatchPaused=true;focusCountdownActive=true;focusCountdownTotalMs=focusSelectedMinutes*60000;focusCountdownEnd=Date.now()+focusCountdownTotalMs;$('#focusCountdownPanel').classList.remove('show');$('#focusCountdownOrb').classList.add('show');$('#focusCountdownStart').textContent='Stop countdown';$('#focusCountdownMessage').textContent='Stopwatch paused · Stay with this one focus block.';updateFocusTimer()}
function stopFocusCountdown(resume=true){if(!focusCountdownActive)return;focusCountdownActive=false;if(resume){focusStopwatchPaused=false;focusStartedAt=Date.now()-focusElapsedMs}$('#focusCountdownOrb').classList.remove('show');$('#focusCountdownStart').textContent='Start countdown';$('#focusCountdownMessage').textContent='The stopwatch pauses while your countdown runs.'}
function finishFocusCountdown(){focusCountdownActive=false;focusStopwatchPaused=false;focusStartedAt=Date.now()-focusElapsedMs;$('#focusCountdownDisplay').textContent='00:00';$('#focusCountdownOrb').classList.remove('show');$('#focusCountdownPanel').classList.add('show');$('#focusCountdownStart').textContent='Start again';$('#focusCountdownMessage').textContent='Focus block complete. Take a breath, then continue.';try{navigator.vibrate?.([180,80,180])}catch{};toast('Focus countdown complete.')}
function openFocusTaskChooser(){let queue=tasks.filter(t=>!t.done&&taskDateISO(t)===localISO());$('#modalBody').innerHTML=`<h2>Choose a focus task</h2><p>Same To Do List—tap Play instead of completing it.</p><div class="queue-list">${queue.map((t,i)=>`<div class="queue-item"><span class="queue-number">${i+1}.</span><div><strong>${escapeHtml(t.title)}</strong><small>${t.time} · ${taskCategory(t)}</small></div><span class="queue-handle">☷</span><button class="focus-play-task" data-focus-play="${t.id}">▶</button></div>`).join('')||'<div class="summary-box">No pending tasks for today.</div>'}</div>`;$('#modal').classList.add('open','focus-chooser');$$('[data-focus-play]').forEach(b=>b.onclick=()=>{let i=tasks.findIndex(t=>t.id===b.dataset.focusPlay);if(i<0)return;let [chosen]=tasks.splice(i,1);tasks.unshift(chosen);store.set('tide_tasks',tasks);renderTasks();$('#modal').classList.remove('open','focus-chooser');refreshFocusTask(true);toast('Focus task changed.')})}
function setupFocusSwipe(){let overlay=$('#focusOverlay'),green=$('#focusGreen'),startX=0,active=false,moved=false;overlay.onpointerdown=e=>{if(e.target.closest('button'))return;active=true;moved=false;startX=e.clientX;overlay.setPointerCapture?.(e.pointerId)};overlay.onpointermove=e=>{if(!active)return;let dx=Math.max(0,e.clientX-startX);if(dx>8)moved=true;if(moved)green.style.width=Math.min(100,dx/overlay.clientWidth*100)+'%'};overlay.onpointerup=overlay.onpointercancel=e=>{if(!active)return;active=false;let dx=Math.max(0,e.clientX-startX);if(dx>overlay.clientWidth*.38&&currentTaskIndex()>=0){overlay.classList.add('completing');green.style.width='100%';setTimeout(()=>{completeCurrentTask();overlay.classList.remove('completing');green.style.width='0';if(currentTaskIndex()>=0)refreshFocusTask(true);else closeFocusMode()},320)}else green.style.width='0'}}
function setupHeroSwipe(){let card=$('#nextCard'),green=$('#heroGreen'),startX=0,active=false,moved=false;card.onpointerdown=e=>{if(e.target.closest('button'))return;active=true;moved=false;startX=e.clientX;card.setPointerCapture?.(e.pointerId);green.style.transition='none'};card.onpointermove=e=>{if(!active)return;let dx=Math.max(0,e.clientX-startX);if(dx>7)moved=true;if(moved){card.classList.add('swiping');green.style.width=Math.min(100,dx/card.clientWidth*100)+'%'}};card.onpointerup=card.onpointercancel=e=>{if(!active)return;active=false;let dx=Math.max(0,e.clientX-startX),done=dx>card.clientWidth*.38;green.style.transition='width .16s ease';card.classList.remove('swiping');if(done&&currentTaskIndex()>=0){card.classList.add('completed-swipe');green.style.width='100%';setTimeout(()=>{completeCurrentTask();card.classList.remove('completed-swipe');green.style.width='0'},260)}else{green.style.width='0';if(!moved){e.preventDefault();e.stopPropagation();setTimeout(()=>openTaskQueue(localISO()),90)}}}}
$('#openQueueBtn').onclick=e=>{e.stopPropagation();openTaskQueue(localISO())};$('#focusModeBtn').onclick=e=>{e.stopPropagation();openFocusMode()};bindFastTap($('#focusClose'),closeFocusMode);$('#focusTimerToggle').onclick=()=>$('#focusBigTimer').classList.toggle('show');$('#focusTaskPicker').onclick=openFocusTaskChooser;$('#focusHourglass').onclick=()=>$('#focusCountdownPanel').classList.toggle('show');$('#focusCountdownOrb').onclick=()=>$('#focusCountdownPanel').classList.add('show');bindFastTap($('#focusCountdownClose'),()=>$('#focusCountdownPanel').classList.remove('show'));$$('[data-focus-minutes]').forEach(b=>b.onclick=()=>{focusSelectedMinutes=+b.dataset.focusMinutes;$$('[data-focus-minutes]').forEach(x=>x.classList.toggle('active',x===b));$('#focusCountdownDisplay').textContent=clockText(focusSelectedMinutes*60000)});$('#focusCountdownStart').onclick=()=>{if(focusCountdownActive)stopFocusCountdown(true);else startFocusCountdown(+$('#focusCustomMinutes').value||focusSelectedMinutes)};$('#nextCard').onkeydown=e=>{if(e.key==='Enter')openTaskQueue(localISO())};setupHeroSwipe();setupFocusSwipe();
$('#themeToggle').onclick=()=>applyTheme(currentTheme==='light'?'dark':'light');$('#searchBtn').onclick=openSearch;
function closeMobileMenu(){$('.sidebar').classList.remove('mobile-open');$('#sidebarOverlay').classList.remove('show')}
$('#mobileMenu').onclick=()=>{$('.sidebar').classList.add('mobile-open');$('#sidebarOverlay').classList.add('show')};$('#sidebarOverlay').onclick=closeMobileMenu;$$('.sidebar [data-tab]').forEach(b=>b.addEventListener('click',closeMobileMenu));
$('#addMeetingPageBtn').onclick=()=>$('#addMeetingBtn').click();$('#addReminderBtn').onclick=openAddReminder;$('#addFollowupBtn').onclick=openAddFollowup;$('#addGeneralTaskBtn').onclick=()=>openQuickAddTask(localISO());$$('[data-open-category]').forEach(card=>card.onclick=e=>{if(!e.target.closest('.category-add'))switchTab(card.dataset.openCategory)});$('#quickAddMeeting').onclick=e=>{e.stopPropagation();$('#addMeetingBtn').click()};$('#quickAddReminder').onclick=e=>{e.stopPropagation();openAddReminder()};$('#quickAddFollowup').onclick=e=>{e.stopPropagation();openAddFollowup()};$('#quickAddTask').onclick=e=>{e.stopPropagation();openQuickAddTask(localISO())};$('#monthFeedPrev').onclick=()=>renderMonthFeed(--monthFeedOffset);$('#monthFeedNext').onclick=()=>renderMonthFeed(++monthFeedOffset);
$('#routineLogBtn').onclick=()=>{let input=$('#routineInput'),entry=trackRoutineEntry(input.value);if(entry)input.value=''};$('#routineInput').onkeydown=e=>{if(e.key==='Enter')$('#routineLogBtn').click()};$$('[data-routine-prompt]').forEach(b=>b.onclick=()=>{$('#routineInput').value=b.dataset.routinePrompt;$('#routineLogBtn').click()});$('#addRoutineScheduleBtn').onclick=openRoutineScheduleModal;$('#editRoutineScheduleBtn').onclick=openRoutineScheduleModal;$('#clearRoutineLog').onclick=()=>{if(confirm('Clear today’s routine entries?')){routineLogs=[];store.set('tide_routine_logs',routineLogs);renderRoutineTracker()}};$$('[data-routine-report]').forEach(b=>b.onclick=()=>renderRoutineReport(b.dataset.routineReport));
function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
applyTheme(currentTheme);updateGreeting();setInterval(updateGreeting,60000);setManualDate();ensureMeetingTasks();normalizeTaskTimes();rollOverPendingTasks();setInterval(()=>{if(rollOverPendingTasks())renderTasks()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&rollOverPendingTasks())renderTasks()});renderTasks();renderThoughts();renderPeople();renderRoutine();renderRoutineTracker();renderRules();renderCalendar();renderTodayCards();renderMonthFeed();
